version:      "{build}"
clone_folder: c:\wkhtmltopdf\wkhtmltopdf
test:         off

environment:
  matrix:
    - TARGET: msvc2015-win32

install:
  - git submodule update --init --recursive --force --depth 50
  - git clone https://github.com/wkhtmltopdf/packaging.git ..\packaging
  - pip install -q conan pyyaml
  - perl -p -i.bak -e "s/quiet = 0/quiet = 1/g" qt/bin/syncqt

build_script:
  - python ..\packaging\build vagrant --version - - %TARGET% c:\wkhtmltopdf\wkhtmltopdf
